# Generated by Django 5.2.5 on 2025-09-05 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
