# Generated by Django 5.2.5 on 2025-09-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_admin_options_alter_kitob_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='mualliy',
            new_name='muallif',
        ),
    ]
